### ISSUE TITLE
Password input is shown in plaintext

### ISSUE THREAD

**Issue by axelolsson** [chas-academy/12-instagram-clone-eleonorbergqvist#3]
![screen shot 2018-05-08 at 08 00 52](https://user-images.githubusercontent.com/343422/39740473-0117ad62-5296-11e8-8a0f-bc43e1026aca.png)

Have we not learned this is how we do this?:

```HTML
<input type="password" placeholder="Please input your password here" />
```

**Comment by eleonorbergqvist** [comment]
Done
